--Tabla Usuarios
create table USUARIOS
(
	E_MAIL			 varchar,
	USUARIO		 	 varchar(20),
	CONTRASEÑA		 varchar(20),
	CONSTRAINT PK_COD_USUARIO PRIMARY KEY (E_MAIL),
);
--Tabla Eventos
create table EVENTOS
(
	CODIGO			 integer(6),
	E_MAIL			 varchar,
	TITULO			 varchar(30),
	DURACION		 integer(4),--En minutos
	DESCRIPCION		 varchar(200),
	FECHAINI	 	 date,
	FECHAFIN	 	 date,
	COD_PERIODO		 integer(6),
	COD_PRIORIDAD		 integer(6),
	CONSTRAINT PK_COD_EVENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_EMAIL FOREIGN KEY (E_MAIL) REFERENCES USUARIOS(E_MAIL)
	CONSTRAINT FK_COD_PERIODO FOREIGN KEY (COD_PERIODO) REFERENCES PERIODOS(CODIGO)
	CONSTRAINT FK_COD_PRIORIDAD FOREIGN KEY (COD_PRIORIDAD) REFERENCES PRIORIDADES(CODIGO)
);
--Tabla Periodos
create table PERIODOS
(
	CODIGO	 integer(6),
	NOMBRE	 varchar(20),
	CONSTRAINT PK_COD_PERIODO PRIMARY KEY (CODIGO)
);
--Tabla Prioridades
create table PRIORIDADES
(
	CODIGO	 integer(6),
	NIVEL	 integer(1),
	CONSTRAINT PK_COD_PRIORIDAD PRIMARY KEY (CODIGO)
);
--Tabla Eventos Pasados
create table EVENTOS_PASADOS
(
	CODIGO			 integer(6),
	TITULO			 varchar(30),
	DESCRIPCION		 varchar(200),
	CONSTRAINT PK_COD_EVENTOPASADO PRIMARY KEY (CODIGO),
);
--Tabla Eventos-Eventospasados
create table DETALLE_EVENTOSPASADOS
(
	COD_EVENTO		integer(6),
	COD_EVENTO_PASADO	integer(6),
	FECHA			date,	----Fecha con la hora de inicio
	HORAFIN			date,
	CONSTRAINT PK_DETALLE_EVENTOS PRIMARY KEY (COD_EVENTO, COD_EVENTO_PASADO, FECHA),
	CONSTRAINT FK_COD_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES (EVENTOS),
	CONSTRAINT FK_COD_EVENTO_PASADO FOREIGN KEY (COD_EVENTO_PASADO) REFERENCES (EVENTOS_PASADOS),
);







